version: "3.9"
services:
  reverse_proxy:
    build:
      context: reverse_proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - backbone
    restart: always
  web-app:
    depends_on:
      - reverse_proxy
    build:
      context: web_server_app
      dockerfile: Dockerfile
    networks:
      - backbone
    expose:
      - 8080
  requester:
    depends_on:
      - web-app
    build:
      context: client_ab_requester
      dockerfile: Dockerfile
    networks:
      - backbone
networks:
  backbone:
    driver: bridge
